import type { BuiltReport } from './report';

export function buildMailto(report: BuiltReport, options: { to?: string } = {}): string {
  const { template, snapshot, totals, issueEntries } = report;
  const meta = snapshot.meta;
  const subject = `Tesla 納車チェック結果 — ${template.modelNameJa}${meta.vin ? ` (VIN: ${meta.vin})` : ''}`;
  const lines: string[] = [];
  lines.push(`お世話になっております。`);
  lines.push(`Tesla 納車チェックの結果をお送りします。`);
  lines.push('');
  lines.push(`■ 車種: ${template.modelNameJa}`);
  if (meta.vin) lines.push(`■ VIN: ${meta.vin}`);
  if (meta.deliveryLocation) lines.push(`■ 納車場所: ${meta.deliveryLocation}`);
  if (meta.ownerName) lines.push(`■ オーナー: ${meta.ownerName}`);
  lines.push('');
  lines.push(`■ 集計: OK ${totals.ok} / 問題 ${totals.issue} / 対象外 ${totals.na} / 未確認 ${totals.unchecked} (合計 ${totals.total})`);
  lines.push('');
  lines.push(`■ 問題があった項目 (${issueEntries.length} 件):`);
  if (issueEntries.length === 0) {
    lines.push('  - なし');
  } else {
    issueEntries.forEach((e, i) => {
      lines.push(`  ${i + 1}. [${e.severity ?? 'minor'}] ${e.title} (${e.category})`);
      if (e.note) lines.push(`     メモ: ${e.note}`);
    });
  }
  lines.push('');
  lines.push('詳細レポート (写真付き HTML / PDF) を別途共有いたしますのでご確認ください。');
  lines.push('');
  lines.push('--');
  lines.push('Generated by tesla-delivery-checklist');

  const body = lines.join('\n');
  const params = new URLSearchParams();
  params.set('subject', subject);
  params.set('body', body);
  const recipient = options.to ?? '';
  return `mailto:${encodeURIComponent(recipient)}?${params.toString()}`;
}
