import type { BuiltReport } from './report';
import type { ItemStatus, Severity } from '@/data/schema';
import { formatDate } from './utils';

const statusLabel: Record<ItemStatus, string> = {
  ok: '✅ OK',
  issue: '⚠️ 問題あり',
  na: '— 対象外',
  unchecked: '◻ 未チェック',
};
const severityLabel: Record<Severity, string> = {
  critical: '🔴 重大',
  major: '🟠 要対応',
  minor: '⚪ 軽微',
};

export function generateMarkdownReport(report: BuiltReport): string {
  const { template, snapshot, totals, entries, issueEntries, generatedAt } = report;
  const meta = snapshot.meta;
  const lines: string[] = [];

  lines.push(`# Tesla 納車チェックレポート — ${template.modelNameJa}`);
  lines.push('');
  lines.push(`- 生成日時: ${formatDate(generatedAt)}`);
  lines.push(`- 開始日時: ${formatDate(snapshot.startedAt)}`);
  lines.push(`- VIN: ${meta.vin || '—'}`);
  lines.push(`- 納車場所: ${meta.deliveryLocation || '—'}`);
  lines.push(`- オーナー: ${meta.ownerName || '—'}`);
  lines.push(`- 担当アドバイザー: ${meta.advisorName || '—'}`);
  lines.push(`- テンプレート: ${template.modelId}@${template.version}`);
  lines.push('');
  lines.push(
    `**集計**: OK ${totals.ok} / 問題 ${totals.issue} / 対象外 ${totals.na} / 未チェック ${totals.unchecked} (合計 ${totals.total})`
  );
  lines.push('');

  lines.push(`## 問題があった項目 (${issueEntries.length} 件)`);
  lines.push('');
  if (issueEntries.length === 0) {
    lines.push('問題として記録された項目はありません。');
  } else {
    for (const e of issueEntries) {
      lines.push(`### ${severityLabel[e.severity ?? 'minor']} ${e.title}`);
      lines.push('');
      lines.push(`- カテゴリ: ${e.category}`);
      if (e.note) {
        lines.push('');
        lines.push('> ' + e.note.replace(/\n/g, '\n> '));
      }
      if (e.media.length > 0) {
        lines.push('');
        lines.push(`添付メディア: ${e.media.length} 件 (HTML レポートに同梱されています)`);
      }
      lines.push('');
    }
  }

  lines.push('## 全項目');
  lines.push('');
  lines.push('| カテゴリ | 項目 | 重要度 | 結果 | メモ |');
  lines.push('|---|---|---|---|---|');
  for (const e of entries) {
    const note = (e.note ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
    lines.push(
      `| ${e.category} | ${e.title} | ${severityLabel[e.severity ?? 'minor']} | ${statusLabel[e.status]} | ${note} |`
    );
  }
  lines.push('');
  lines.push('---');
  lines.push('_Generated by tesla-delivery-checklist_');

  return lines.join('\n');
}
